spring:
  datasource:
    url: jdbc:postgresql://api-rest-clinica-veterinaria.railway.internal:5432/railway
    username: postgres
    password: DLBRqzQZEJZMvlqBTpbLEfTprxSUVHoH
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create